name: Troling
main: com.trollplayer.trollmain
version: 1.3.1
database: false
authors: [Razdom, BeatsDJ, dannycool1031]
website: http://dev.bukkit.org/bukkit-plugins/troling/
description: This plugin allow you to troll your friends!
commands:
  troling:
      description: cradits!
      usage: /<command>
  troll:
      description: troll players!
      usage: /<command> [player]
      permission: troling.players
      permission-message: You don`t have <permission>
  trollme:
      description: troll me!
      usage: /<command>
      permission: troling.me
      permission-message: You don`t have <permission>
permissions:
  troling.*:
    description: Gives access to all troling commands.
    children:
      troling.me: true
      troling.players: true
  troling.players:
    default: op
    description: Gives access to all troll command.
  troling.me:
    description: Gives access to all trollme command.
    default: op
